version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: test-enerkom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maulida1010
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test-enerkom
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: maulida1010
    depends_on:
      - db
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
